
#ifndef SRC_CONFIGURATION_PHYSICS_DISCRETIZATION_H_
#define SRC_CONFIGURATION_PHYSICS_DISCRETIZATION_H_

namespace espreso {

enum class DISCRETIZATION {
	FEM = 0,
	BEM = 1
};

}



#endif /* SRC_CONFIGURATION_PHYSICS_DISCRETIZATION_H_ */
