

def configure(ctx):
    ctx.env.append_unique("LIB", [ "feti4i" ])
    ctx.env.append_unique("LIBPATH", ctx.ROOT + "/libespreso")


def build(ctx):
    ctx.program(
        source       = "apitest.cpp",
        target       = "apitest",
        use          = "generator ansys_in espreso_in openfoam_in espreso_out generic_out paraview_out assembler factory feti4i",
        install_path = ctx.ROOT + "/libespreso"
    )
