
def options(opt):
    opt.solvers.add_option("--skip-wsmp", action="store_true", default=False, help="Skip search for WSMP library.")

def configure(ctx):
    if (ctx.options.skip_wsmp):
        return
    libs = [ "pwsmp64" ]
    if ctx.options.cxx == "icpc":
        libs.append("ifcore")
    if ctx.options.cxx == "g++":
        libs.append("gfortran")
        libs.append("pthread")

    ctx.check_cxx(mandatory=False, msg="Checking for 'wpsm'", okmsg=" ".join(libs), define_name="HAVE_WPSM", header_name="wsmp.h", lib=libs, uselib_store="WPSM")