
import os

def options(opt):
    pass

def configure(ctx):
    # assuming only intel oneapi for now
    # assuming intel toolkit 2024+

    ctx.env.append_unique("CXXFLAGS", [ "-fsycl" ])

    headers = [ "sycl/sycl.hpp", "oneapi/mkl.hpp" ]
    libs = [ "sycl", "mkl_sycl_blas", "mkl_sycl_sparse", "mkl_core", "mkl_sequential", "mkl_intel_lp64" ]
    ctx.check_cxx(mandatory=False, msg="Checking for 'oneapi'", okmsg=" ".join(libs), define_name="HAVE_ONEAPI", header_name=headers, lib=libs, uselib_store="ONEAPI", global_define=0)

    ctx.env.CXXFLAGS.remove("-fsycl")

    if ctx.env.HAVE_ONEAPI:
        ctx.env.append_unique("CXXFLAGS_ONEAPI", [ "-fsycl" ])
        ctx.env.append_unique("CXXFLAGS_ONEAPI", [ "-DESPRESO_RANK_TO_GPU_MAP=" + ctx.options.rank_to_gpu_map ])
        
