import os

def options(opt):
    opt.math.add_option("--blas_libraries", action="store", type="string", default=os.getenv("BLAS_LIBRARIES") or "blas", help="List of BLAS libraries.")
    opt.math.add_option("--skip-blas", action="store_true", default=False, help="Skip search for LAPACK library.")

def configure(ctx):
    if (ctx.options.skip_blas):
        return

    ctx.check_cxx(mandatory=False, msg="Checking for 'blas'", okmsg=ctx.options.blas_libraries, define_name="HAVE_BLAS", header_name="cblas.h", lib=ctx.options.blas_libraries, uselib_store="BLAS", global_define=0)
