
#ifndef SRC_WRAPPERS_SUPERLU_DIST_SUPERLU_DIST_COMMON_H
#define SRC_WRAPPERS_SUPERLU_DIST_SUPERLU_DIST_COMMON_H



#include <superlu_ddefs.h>



#endif /* SRC_WRAPPERS_SUPERLU_DIST_SUPERLU_DIST_COMMON_H */
