
def options(opt):
    opt.decomposers.add_option("--skip-scotch", action="store_true", default=False, help="Skip search for Scotch library.")

def configure(ctx):
    fragment = "#include \"scotch.h\"\nint main(int argc, char** argv) {{ return sizeof(SCOTCH_Num) != sizeof(esint); }}\n"
    ctx.check_cxx(mandatory=False, msg="Checking for 'scotch'", okmsg="scotch", define_name="HAVE_SCOTCH", header_name="cstdio cstdint scotch.h", lib="scotch scotcherr", fragment=fragment, uselib_store="SCOTCH")
