
def configure(ctx):
    ctx.recurse("esdata")
    ctx.recurse("ansys")
    ctx.recurse("meshgenerator")

def build(ctx):
    ctx.recurse("esdata")
    ctx.recurse("ansys")
    ctx.recurse("meshgenerator")
