
def configure(ctx):
    ctx.recurse("ansys")
    ctx.recurse("meshgenerator")

def build(ctx):
    ctx.recurse("ansys")
    ctx.recurse("meshgenerator")

    ctx(
        export_includes = ".",
        name            = "input_includes"
    )
