
def options(opt):
    pass

def configure(ctx):
    fragment = "#include \"metis.h\"\nint main(int argc, char** argv) {{ \n#ifdef H5_HAVE_PARALLEL\n return 0;\n#endif\nreturn 1;\n }}\n".format(ctx.options.intwidth)
    ctx.check_cxx(mandatory=False, msg="Checking for 'hdf5'", okmsg="hdf5", define_name="HAVE_HDF5", header_name="hdf5.h", lib="hdf5 z", fragment=fragment, uselib_store="HDF5")
