
def options(opt):
    opt.solvers.add_option("--superlu", action="store", type="string", metavar="SUPERLU_ROOT", default="", help="Path to Super LU (distributed) library.")

def configure(ctx):
    if int(ctx.options.intwidth) == 32:
        ctx.link_cxx(name="superlu", header_name="superlu_ddefs.h superlu_dist_config.h util_dist.h", libs=["superlu_dist"], root=ctx.options.superlu)
