
source_files = (
    "ansys.cpp",
)

def configure(ctx):
    pass

def build(ctx):
    ctx.lib(
        source          = source_files,
        target          = "esinput_ansys",
        use             = "espreso_includes",
        install_path    = ctx.LIBRARIES
    )
