
include: tests/test_groups.yml

stages:
  - build
  - solver
  - release

.ws_build:
  stage: build
  tags:
    - ws

.ws_foss:
  extends: .ws_build
  before_script:
    - export CXX=mpic++

.ws_mkl:
  extends: .ws_build
  before_script:
    - export CXX=mpic++
    - export CPATH=/usr/include/mkl:$CPATH

.ws_intel:
  extends: .ws_build
  before_script:
    - . env/modules.workstation.icpc

.ws_solver_foss:
  extends: .ws_foss
  stage: solver
  only:
    refs:
      - schedules

.ws_solver_mkl:
  extends: .ws_mkl
  stage: solver
  only:
    refs:
      - schedules

.ws_solver_intel:
  extends: .ws_intel
  stage: solver
  only:
    refs:
      - schedules

.snippets:
  dummy: # build without any third-party library
    - ./waf configure --skip-suitesparse --skip-mkl --skip-blas --skip-lapack
    - ./waf -j8
    - ./waf configure --skip-suitesparse --skip-mkl --skip-blas --skip-lapack --intwidth=64
    - ./waf -j8
  basic: # fast tests that includes calling of third-party libraries
    - ./waf configure
    - ./waf -j 8
    - !reference [.basic, script]
    - ./waf configure --intwidth=64
    - ./waf -j 8
    - !reference [.basic, script]
  assembler:
    - ./waf configure
    - ./waf -j 8
    - !reference [.assembler, script]
    - ./waf configure --intwidth=64
    - ./waf -j 8
    - !reference [.assembler, script]
  physical_solver: # only 32-bit int due to MKL-PDSS
    - ./waf configure
    - ./waf -j 8
    - !reference [.physical_solver, script]
  feti:
    - ./waf configure
    - ./waf -j 8
    - !reference [.feti, script]
    - ./waf configure --intwidth=64
    - ./waf -j 8
    - !reference [.feti, script]

WS_DUMMY:
  extends: .ws_foss
  script:
    - !reference [.snippets, dummy]

WS_FOSS:
  extends: .ws_foss
  script:
    - !reference [.snippets, basic]

WS_MKL:
  extends: .ws_mkl
  script:
    - !reference [.snippets, basic]

WS_INTEL:
  extends: .ws_intel
  script:
    - !reference [.snippets, basic]

WS_ASSEMBLER:
  extends: .ws_solver_intel
  script:
    - !reference [.snippets, assembler]

WS_PHYSICAL_SOLVER:
  extends: .ws_solver_intel
  script:
    - !reference [.snippets, physical_solver]

WS_FETI:
  extends: .ws_solver_foss
  script:
    - !reference [.snippets, feti]

GITHUB:
  stage: release
  script:
    - if ! git remote | grep release > /dev/null; then
        git remote add release git@github.com:It4innovations/espreso.git;
      fi
