variables:
  GIT_STRATEGY: fetch

stages:
  - tests
  - release

before_script:
  - source /opt/intel/bin/compilervars.sh intel64
  - . env/paths.default
  - . env/threading.default 5
  - cp build/build.config.icpc build.config

after_script:
  - ./waf distclean
  - rm -fr libs*
  - rm espreso
  - rm decomposer

MKL32:
  stage: tests
  only:
    - triggers
  script:
    - ./waf configure --SOLVER=MKL --INT_WIDTH=32
    - ./waf install -j8
    - python tests/benchmarks.py
    - python tests/input.py
    - python tests/solver.py

MKL64:
  stage: tests
  only:
    - triggers
  script:
    - ./waf configure --SOLVER=MKL --INT_WIDTH=64
    - ./waf install -j8
    - python tests/benchmarks.py
    - python tests/input.py
    - python tests/solver.py

CUDA32:
  stage: tests
  only:
    - triggers
  script:
    - ./waf configure --SOLVER=CUDA --INT_WIDTH=32
    - ./waf install -j8

CUDA64:
  stage: tests
  only:
    - triggers
  script:
    - ./waf configure --SOLVER=CUDA --INT_WIDTH=64
    - ./waf install -j8

PARDISO32:
  stage: tests
  only:
    - triggers
  script:
    - ./waf configure --SOLVER=PARDISO --INT_WIDTH=32 --LIBPATH=/opt/pardiso/
    - ./waf install -j8
    - export PARDISOLICMESSAGE=1
    - echo $PARDISO_LICENCE > pardiso.lic
    - export PARDISO_LIC_PATH=$PWD
    - export LD_LIBRARY_PATH=/opt/pardiso/:$LD_LIBRARY_PATH

STATIC_LIBRARY:
  stage: tests
  only:
    - triggers
  script:
    - ./waf configure --LIBTYPE=STATIC
    - ./waf install -j8
    - python tests/benchmarks.py
    - python tests/input.py
    - python tests/solver.py

HYPRE:
  stage: tests
  only:
    - triggers
  script:
    - ./waf configure --HYPRE::INCLUDE=/opt/hypre/include --HYPRE::LIBPATH=/opt/hypre/lib
    - ./waf install -j8

VTK:
  stage: tests
  only:
    - triggers
  script:
    - ./waf configure --VTK::INCLUDE=/opt/vtk/include/vtk-7.1 --VTK::LIBPATH=/opt/vtk/lib
    - ./waf install -j8
    - export LD_LIBRARY_PATH=/opt/vtk/lib/:$LD_LIBRARY_PATH


GITHUB:
  stage: release
  only:
    - triggers
  script:
    - echo "push to GitHub"
