
stages:
  - build
  - solver
  - release

.ws_build:
  stage: build
  tags:
    - ws

.ws_foss:
  extends: .ws_build
  before_script:
    - export CXX=mpic++

.ws_mkl:
  extends: .ws_build
  before_script:
    - export CXX=mpic++
    - export CPATH=/usr/include/mkl:$CPATH

.ws_intel:
  extends: .ws_build
  before_script:
    - . env/modules.workstation.icpc

.ws_solver_foss:
  extends: .ws_foss
  stage: solver
  only:
    refs:
      - schedules

.ws_solver_mkl:
  extends: .ws_mkl
  stage: solver
  only:
    refs:
      - schedules

.ws_solver_intel:
  extends: .ws_intel
  stage: solver
  only:
    refs:
      - schedules

.cs_build:
  stage: build
  tags:
    - cs
  before_script:
    - salloc -A $PROJECT_ID -p p01-arm -N 1 -n 48 -J $CI_JOB_ID --no-shell
    - export SLURM_JOB_ID="$(squeue -o %A -h -t R -n $CI_JOB_ID)"
    - sh env/suitesparse.clone.sh _a64fx
    - cat tests/scripts/env/header.sh >> job.$CI_JOB_ID.sh
    - cat tests/scripts/env/a64fx.cs.sh >> job.$CI_JOB_ID.sh
  after_script:
    - scancel "$(squeue -o %A -h -t R -n $CI_JOB_ID)"

WS_DUMMY:
  extends: .ws_foss
  script:
    - sh tests/scripts/dummy.sh -j8

WS_FOSS:
  extends: .ws_foss
  script:
    - sh tests/scripts/basic.sh -j8

WS_MKL:
  extends: .ws_mkl
  script:
    - sh tests/scripts/basic.sh -j8

WS_INTEL:
  extends: .ws_intel
  script:
    - sh tests/scripts/basic.sh -j8

WS_ASSEMBLER:
  extends: .ws_solver_intel
  script:
    - sh tests/scripts/assembler.sh -j8

WS_PHYSICAL_SOLVER:
  extends: .ws_solver_intel
  script:
    - sh tests/scripts/physical_solver.sh -j8

WS_FETI:
  extends: .ws_solver_foss
  script:
    - sh tests/scripts/feti.sh -j8

CS_DUMMY:
  extends: .cs_build
  script:
    - cat tests/scripts/dummy.sh >> job.$CI_JOB_ID.sh
    - srun sh job.$CI_JOB_ID.sh

CS_FOSS:
  extends: .cs_build
  script:
    - cat tests/scripts/basic.sh >> job.$CI_JOB_ID.sh
    - srun sh job.$CI_JOB_ID.sh

.GITHUB:
  stage: release
  script:
    - if ! git remote | grep release > /dev/null; then
        git remote add release git@github.com:It4innovations/espreso.git;
      fi
