stages:
  - build
  - mesio
  - espreso
  - feti4i
  - release

before_script:
  - export SPACK_ROOT=/opt/spack
  - . $SPACK_ROOT/share/spack/setup-env.sh
  - export PATH=$PWD/build/:$PATH
  - export LD_LIBRARY_PATH=$PWD/build/:$LD_LIBRARY_PATH 
  - . $PWD/env/modules.workstation

PYTHON:
  stage: build
  only:
    refs:
      - schedules
    variables:
      - $BUILD
      - $FULL
  script:
    - python2 waf configure -mdebug
    - python2 waf -j8
    - nosetests -v benchmarks/dummy
    - python3 waf configure -mdebug
    - python3 waf -j8
    - nosetests -v benchmarks/dummy

INT32:
  stage: build
  only:
    refs:
      - schedules
    variables:
      - $BUILD
      - $FULL
  script:
    - ./waf configure
    - ./waf -j8
    - nosetests -v benchmarks/dummy

INT64:
  stage: build
  only:
    refs:
      - schedules
    variables:
      - $BUILD
      - $FULL
  script:
    - ./waf configure --intwidth=64
    - ./waf -j8
    - nosetests -v benchmarks/dummy

STATIC:
  stage: build
  only:
    refs:
      - schedules
    variables:
      - $BUILD
      - $FULL
  script:
    - ./waf configure --static
    - ./waf --static --libs="dl" -j8
    - nosetests -v benchmarks/dummy

PROFILE:
  stage: build
  only:
    refs:
      - schedules
    variables:
      - $BUILD
      - $FULL
  script:
    - ./waf configure -mprofile
    - ./waf -j8
    - nosetests -v benchmarks/dummy


DUMMY_WRAPPERS:
  stage: build
  only:
    refs:
      - schedules
    variables:
      - $BUILD
      - $FULL
  script:
    - ml purge
    - . $PWD/env/modules.workstation.mpi_only
    - ./waf configure
    - ./waf -j8

GUI:
  stage: build
  only:
    refs:
      - schedules
    variables:
      - $BUILD
      - $FULL
  script:
    - ./waf configure --with-gui
    - ./waf -j8

HEAT:
  stage: espreso
  only:
    refs:
      - schedules
    variables:
      - $ESPRESO
      - $FULL
  script:
    - ./waf configure
    - ./waf -j8
    - nosetests -v benchmarks/advectionDiffusion2D
    - nosetests -v benchmarks/advectionDiffusion3D
    - nosetests -v benchmarks/diffusion2D
    - nosetests -v benchmarks/diffusion3D

MORPHING:
  stage: espreso
  only:
    refs:
      - schedules
    variables:
      - $ESPRESO
      - $MORPHING
      - $FULL
  script:
    - ./waf configure
    - ./waf -j8
    - nosetests -v benchmarks/diffusion3D/steadystate/morphing

ELASTICITY:
  stage: espreso
  only:
    refs:
      - schedules
    variables:
      - $ESPRESO
      - $FULL
  script:
    - ./waf configure
    - ./waf -j8
    - nosetests -v benchmarks/linearElasticity2D
    - nosetests -v benchmarks/linearElasticity3D

CUDA_SOLVER:
  stage: espreso
  only:
    refs:
      - schedules
    variables:
      - $CUDA
      - $FULL
  script:
    - ./waf configure --solver=cuda
    - ./waf -j8
    - nosetests -v benchmarks/cudasolver

FETI_SOLVER:
  stage: espreso
  only:
    refs:
      - schedules
    variables:
      - $ESPRESO
      - $FULL
  script:
    - ./waf configure
    - ./waf -j8
    - nosetests -v benchmarks/fetisolver

INPUT32:
  stage: mesio
  only:
    refs:
      - schedules
    variables:
      - $MESIO
      - $FULL
  script:
    - ./waf configure
    - ./waf -j8
    - nosetests -v benchmarks/input

INPUT64:
  stage: mesio
  only:
    refs:
      - schedules
    variables:
      - $MESIO
      - $FULL
  script:
    - ./waf configure --intwidth=64
    - ./waf -j8
    - nosetests -v benchmarks/input/brake

OUTPUT32:
  stage: mesio
  only:
    refs:
      - schedules
    variables:
      - $MESIO
      - $FULL
  script:
    - ./waf configure
    - ./waf -j8
    - nosetests -v benchmarks/output

OUTPUT64:
  stage: mesio
  only:
    refs:
      - schedules
    variables:
      - $MESIO
      - $FULL
  script:
    - ./waf configure --intwidth=64
    - ./waf -j8
    - nosetests -v benchmarks/output/brake

CONTACT:
  stage: mesio
  only:
    refs:
      - schedules
    variables:
      - $MESIO
      - $FULL
  script:
    - ./waf configure
    - ./waf -j8
    - nosetests -v benchmarks/contact

APITEST:
  stage: feti4i
  only:
    refs:
      - schedules
    variables:
      - $API
      - $FULL
  script:
    - ./waf configure
    - ./waf -j8
    - nosetests -v benchmarks/feti4i

GITHUB:
  stage: release
  only:
    refs:
      - schedules
    variables:
      - $FULL
  script:
    - if ! git remote | grep release > /dev/null; then
        git remote add release git@github.com:It4innovations/espreso.git;
      fi
    - git checkout master
    - git pull origin master
    - git push release master
