variables:
  GIT_STRATEGY: fetch

stages:
  - tests
  - release

before_script:
  - source /opt/intel/bin/compilervars.sh intel64
  - . env/paths.default
  - . env/threading.default 5
  - cp install/build.config.icpc build.config

after_script:
  - ./waf distclean
  - rm -fr libs*
  - rm espreso
  - rm decomposer

MKL32:
  stage: tests
  only:
    - triggers
  script:
    - ./waf configure --SOLVER=MKL --INT_WIDTH=32
    - ./waf install -j8
    - python tests/benchmarks.py
    - python tests/input.py
    - python tests/solver.py

MKL64:
  stage: tests
  only:
    - triggers
  script:
    - ./waf configure --SOLVER=MKL --INT_WIDTH=64
    - ./waf install -j8
    - python tests/benchmarks.py
    - python tests/input.py
    - python tests/solver.py

CUDA32:
  stage: tests
  only:
    - triggers
  script:
    - ./waf configure --SOLVER=CUDA --INT_WIDTH=32
    - ./waf install -j8

CUDA64:
  stage: tests
  only:
    - triggers
  script:
    - ./waf configure --SOLVER=CUDA --INT_WIDTH=64
    - ./waf install -j8

STATIC_LIBRARY:
  stage: tests
  only:
    - triggers
  script:
    - ./waf configure --LIBTYPE=STATIC
    - ./waf install -j8
    - python tests/benchmarks.py
    - python tests/input.py
    - python tests/solver.py

CATALYST:
  stage: tests
  only:
    - triggers
  script:
    - ./waf configure --CATALYST::INCLUDE=/opt/vtk/include/vtk-7.1 --CATALYST::LIBPATH=/opt/vtk/lib
    - ./waf install -j8
    - export LD_LIBRARY_PATH=/opt/vtk/lib/:$LD_LIBRARY_PATH


GITHUB:
  stage: release
  only:
    - triggers
  script:
    - echo "push to GitHub"
