stages:
  - build
  - solver
  - release

before_script:
  - export CXX=mpic++

WS_DUMMY:
  stage: build
  script:
    - ./waf configure --skip-suitesparse --skip-mkl --skip-blas --skip-lapack
    - ./waf -j8

    - ./waf configure --skip-suitesparse --skip-mkl --skip-blas --skip-lapack --intwidth=64
    - ./waf -j8

WS_MKL:
  stage: build
  script:
    - export CPATH=/usr/include/mkl:$CPATH

    - ./waf configure
    - ./waf -j8
    - nose2 -v -s tests/heatTransfer/const/conductivity/isotropic2D/
    - nose2 -v -s tests/heatTransfer/const/conductivity/isotropic3D/
    - nose2 -v -s tests/linearElasticity/const/planeStrain/elements/acceleration/
    - nose2 -v -s tests/linearElasticity/const/volume/element/acceleration/

    - ./waf configure --intwidth=64
    - ./waf -j8
    - nose2 -v -s tests/heatTransfer/const/conductivity/isotropic2D/
    - nose2 -v -s tests/heatTransfer/const/conductivity/isotropic3D/
    - nose2 -v -s tests/linearElasticity/const/planeStrain/elements/acceleration/
    - nose2 -v -s tests/linearElasticity/const/volume/element/acceleration/

WS_FOSS:
  stage: build
  script:
    - ./waf configure
    - ./waf -j8
    - nose2 -v -s tests/heatTransfer/const/conductivity/isotropic2D/
    - nose2 -v -s tests/heatTransfer/const/conductivity/isotropic3D/
    - nose2 -v -s tests/linearElasticity/const/planeStrain/elements/acceleration/
    - nose2 -v -s tests/linearElasticity/const/volume/element/acceleration/

    - ./waf configure --intwidth=64
    - ./waf -j8
    - nose2 -v -s tests/heatTransfer/const/conductivity/isotropic2D/
    - nose2 -v -s tests/heatTransfer/const/conductivity/isotropic3D/
    - nose2 -v -s tests/linearElasticity/const/planeStrain/elements/acceleration/
    - nose2 -v -s tests/linearElasticity/const/volume/element/acceleration/

WS_INTEL:
  stage: build
  script:
    - . env/modules.workstation.icpc

    - ./waf configure
    - ./waf -j8
    - nose2 -v -s tests/heatTransfer/const/conductivity/anisotropic2D/
    - nose2 -v -s tests/heatTransfer/const/conductivity/anisotropic3D/
    - nose2 -v -s tests/linearElasticity/const/planeStrain/elements/acceleration/
    - nose2 -v -s tests/linearElasticity/const/volume/element/acceleration/

    - ./waf configure --intwidth=64
    - ./waf -j8
    - nose2 -v -s tests/heatTransfer/const/conductivity/isotropic2D/
    - nose2 -v -s tests/heatTransfer/const/conductivity/isotropic3D/
    - nose2 -v -s tests/linearElasticity/const/planeStrain/elements/acceleration/
    - nose2 -v -s tests/linearElasticity/const/volume/element/acceleration/

WS_ASSEMBLER:
  stage: solver
  only:
    refs:
      - schedules
  script:
    - . env/modules.workstation.icpc

    - ./waf configure
    - ./waf -j8
    - nose2 -v -s tests/heatTransfer/
    - nose2 -v -s tests/linearElasticity/

    - ./waf configure --intwidth=64
    - ./waf -j8
    - nose2 -v -s tests/heatTransfer/
    - nose2 -v -s tests/linearElasticity/

WS_PHYSICAL_SOLVER:
  stage: solver
  only:
    refs:
      - schedules
  script:
    - . env/modules.workstation.icpc

    - ./waf configure
    - ./waf -j8
    - nose2 -v - s tests/physicalSolver

WS_FETI:
  stage: solver
  only:
    refs:
      - schedules
  script:
    - ./waf configure
    - ./waf -j8
    - nose2 -c tests/nose2.cfg -A feti -v -s tests/heatTransfer/
    - nose2 -c tests/nose2.cfg -A feti -v -s tests/linearElasticity/
    - nose2 -c tests/nose2.cfg         -v -s tests/feti/

    - ./waf configure --intwidth=64
    - ./waf -j8
    - nose2 -c tests/nose2.cfg -A feti -v -s tests/heatTransfer/
    - nose2 -c tests/nose2.cfg -A feti -v -s tests/linearElasticity/
    - nose2 -c tests/nose2.cfg         -v -s tests/feti/

GITHUB:
  stage: release
  script:
    - if ! git remote | grep release > /dev/null; then
        git remote add release git@github.com:It4innovations/espreso.git;
      fi
