
stages:
  - DUMMY
  - INTEL
  - FOSS
  - FOSS_MKL

.ws:
  when: always
  tags:
    - ws
  script:
    - ./waf configure
    - ./waf -j8

# ----------------------------------------------------------------------------------------------- #
#                        DUMMY INSTALATION WITHOUT ANY THIRD-PARTY LIBRARY                        #
# ----------------------------------------------------------------------------------------------- #

INSTALL_32_DUMMY_WS:
  extends: .ws
  stage: DUMMY
  cache:
    key: deps-dummy-32
    paths:
      - dependencies
      - build
  before_script:
    - . env/workstation.foss.32.sh
  script:
    - ./waf configure --skip-suitesparse --skip-mkl --skip-blas --skip-lapack
    - ./waf -j8

INSTALL_64_DUMMY_WS:
  extends: .ws
  stage: DUMMY
  cache:
    key: deps-dummy-64
    paths:
      - dependencies
      - build
  before_script:
    - . env/workstation.foss.64.sh
  script:
    - ./waf configure --skip-suitesparse --skip-mkl --skip-blas --skip-lapack
    - ./waf -j8

# ----------------------------------------------------------------------------------------------- #
#                                     INTEL MPI + INTEL MKL                                       #
# ----------------------------------------------------------------------------------------------- #

INSTALL_32_WS_INTEL:
  extends: .ws
  stage: INTEL
  cache:
    key: deps-intel-32
    paths:
      - dependencies
      - build
  before_script:
    - . env/workstation.intel.32.sh

BASIC_32_WS_INTEL:
  extends: INSTALL_32_WS_INTEL
  script:
    - sh tests/run.basic.sh

ASSEMBLER_32_WS_INTEL:
  extends: INSTALL_32_WS_INTEL
  script:
    - sh tests/run.assembler.sh

PHYSICS_32_WS_INTEL:
  extends: INSTALL_32_WS_INTEL
  script:
    - sh tests/run.physical_solver.sh

FETI_32_WS_INTEL:
  extends: INSTALL_32_WS_INTEL
  script:
    - sh tests/run.feti.sh

INSTALL_64_WS_INTEL:
  extends: .ws
  stage: INTEL
  cache:
    key: deps-intel-64
    paths:
      - dependencies
      - build
  before_script:
    - . env/workstation.intel.64.sh

BASIC_64_WS_INTEL:
  extends: INSTALL_64_WS_INTEL
  script:
    - sh tests/run.basic.sh

ASSEMBLER_64_WS_INTEL:
  extends: INSTALL_64_WS_INTEL
  script:
    - sh tests/run.assembler.sh

PHYSICS_64_WS_INTEL:
  extends: INSTALL_64_WS_INTEL
  script:
    - sh tests/run.physical_solver.sh

FETI_64_WS_INTEL:
  extends: INSTALL_64_WS_INTEL
  script:
    - sh tests/run.feti.sh

# ----------------------------------------------------------------------------------------------- #
#                                    OPEN MPI + SUITESPARSE                                       #
# ----------------------------------------------------------------------------------------------- #

INSTALL_32_WS_FOSS:
  extends: .ws
  stage: FOSS
  cache:
    key: deps-foss-32
    paths:
      - dependencies
      - build
  before_script:
    - . env/workstation.foss.32.sh

BASIC_32_WS_FOSS:
  extends: INSTALL_32_WS_FOSS
  script:
    - sh tests/run.basic.sh

ASSEMBLER_32_WS_FOSS:
  extends: INSTALL_32_WS_FOSS
  script:
    - sh tests/run.assembler.sh

PHYSICS_32_WS_FOSS:
  extends: INSTALL_32_WS_FOSS
  script:
    - sh tests/run.physical_solver.sh

FETI_32_WS_FOSS:
  extends: INSTALL_32_WS_FOSS
  script:
    - sh tests/run.feti.sh

INSTALL_64_WS_FOSS:
  extends: .ws
  stage: FOSS
  cache:
    key: deps-foss-64
    paths:
      - dependencies
      - build
  before_script:
    - . env/workstation.foss.64.sh

BASIC_64_WS_FOSS:
  extends: INSTALL_64_WS_FOSS
  script:
    - sh tests/run.basic.sh

ASSEMBLER_64_WS_FOSS:
  extends: INSTALL_64_WS_FOSS
  script:
    - sh tests/run.assembler.sh

PHYSICS_64_WS_INTEL:
  extends: INSTALL_64_WS_FOSS
  script:
    - sh tests/run.physical_solver.sh

FETI_64_WS_INTEL:
  extends: INSTALL_64_WS_FOSS
  script:
    - sh tests/run.feti.sh

# ----------------------------------------------------------------------------------------------- #
#                                         OPEN MPI + MKL                                          #
# ----------------------------------------------------------------------------------------------- #

INSTALL_32_WS_FOSS_MKL:
  extends: .ws
  stage: FOSS_MKL
  cache:
    key: deps-foss-32
    paths:
      - dependencies
      - build
  before_script:
    - . env/workstation.foss.mkl.32.sh

BASIC_32_WS_FOSS_MKL:
  extends: INSTALL_32_WS_FOSS_MKL
  script:
    - sh tests/run.basic.sh

ASSEMBLER_32_WS_FOSS_MKL:
  extends: INSTALL_32_WS_FOSS_MKL
  script:
    - sh tests/run.assembler.sh

PHYSICS_32_WS_FOSS_MKL:
  extends: INSTALL_32_WS_FOSS_MKL
  script:
    - sh tests/run.physical_solver.sh

FETI_32_WS_FOSS_MKL:
  extends: INSTALL_32_WS_FOSS_MKL
  script:
    - sh tests/run.feti.sh

INSTALL_64_WS_FOSS_MKL:
  extends: .ws
  stage: FOSS
  cache:
    key: deps-foss-64
    paths:
      - dependencies
      - build
  before_script:
    - . env/workstation.foss.mkl.64.sh

BASIC_64_WS_FOSS_MKL:
  extends: INSTALL_64_WS_FOSS_MKL
  script:
    - sh tests/run.basic.sh

ASSEMBLER_64_WS_FOSS_MKL:
  extends: INSTALL_64_WS_FOSS_MKL
  script:
    - sh tests/run.assembler.sh

PHYSICS_64_WS_INTEL_MKL:
  extends: INSTALL_64_WS_FOSS_MKL
  script:
    - sh tests/run.physical_solver.sh

FETI_64_WS_INTEL_MKL:
  extends: INSTALL_64_WS_FOSS_MKL
  script:
    - sh tests/run.feti.sh



