stages:
  - build
  - release

before_script:
  - export CPATH=/usr/include/mkl:$CPATH
  - export CPATH=/usr/include/suitesparse:$CPATH
  - export CXX=mpic++

INT32:
  stage: build
  script:
    - ./waf configure
    - ./waf -j8

INT64:
  stage: build
  script:
    - ./waf configure --intwidth=64
    - ./waf -j8

GITHUB:
  stage: release
  script:
    - if ! git remote | grep release > /dev/null; then
        git remote add release git@github.com:It4innovations/espreso.git;
      fi
