stages:
  - build
  - release

before_script:
  - export CXX=mpic++

DUMMY:
  stage: build
  script:
    - ./waf configure --skip-suitesparse --skip-mkl
    - ./waf -j8

    - ./waf configure --skip-suitesparse --skip-mkl --intwidth=64
    - ./waf -j8

MKL:
  stage: build
  script:
    - export CPATH=/usr/include/mkl:$CPATH

    - ./waf configure
    - ./waf -j8
    - nose2 -v -s tests/heatTransfer/const/conductivity/isotropic2D/
    - nose2 -v -s tests/heatTransfer/const/conductivity/isotropic3D/
    - nose2 -v -s tests/linearElasticity/const/planeStrain/elements/acceleration/
    - nose2 -v -s tests/linearElasticity/const/volume/element/acceleration/

    - ./waf configure --intwidth=64
    - ./waf -j8
    - nose2 -v -s tests/heatTransfer/const/conductivity/isotropic2D/
    - nose2 -v -s tests/heatTransfer/const/conductivity/isotropic3D/
    - nose2 -v -s tests/linearElasticity/const/planeStrain/elements/acceleration/
    - nose2 -v -s tests/linearElasticity/const/volume/element/acceleration/

FOSS:
  stage: build
  script:
    - ./waf configure
    - ./waf -j8
    - nose2 -v -s tests/heatTransfer/const/conductivity/isotropic2D/
    - nose2 -v -s tests/heatTransfer/const/conductivity/isotropic3D/
    - nose2 -v -s tests/linearElasticity/const/planeStrain/elements/acceleration/
    - nose2 -v -s tests/linearElasticity/const/volume/element/acceleration/

    - ./waf configure --intwidth=64
    - ./waf -j8
    - nose2 -v -s tests/heatTransfer/const/conductivity/isotropic2D/
    - nose2 -v -s tests/heatTransfer/const/conductivity/isotropic3D/
    - nose2 -v -s tests/linearElasticity/const/planeStrain/elements/acceleration/
    - nose2 -v -s tests/linearElasticity/const/volume/element/acceleration/

GITHUB:
  stage: release
  script:
    - if ! git remote | grep release > /dev/null; then
        git remote add release git@github.com:It4innovations/espreso.git;
      fi
