
def options(opt):
    opt.solvers.add_option("--skip-pardiso", action="store_true", default=False, help="Skip search for Pardiso library.")

def configure(ctx):
    if (ctx.options.skip_pardiso):
        return
    if int(ctx.options.intwidth) == 32:
        ctx.check_cxx(mandatory=False, msg="Checking for 'pardiso'", okmsg="pardiso", define_name="HAVE_PARDISO", header_name="pardiso.h", lib="pardiso gfortran gomp", uselib_store="PARDISO", global_define=0)