
def configure(ctx):
    ctx.env.append_unique("LIB", [ "z" ])
    ctx.check_lib("z")

def build(ctx):
    ctx.objects(
        source = ctx.path.ant_glob('**/*.cpp'),
        target = "openfoam_in",
        use    = "espreso_includes"
    )
