
source_files =  (
    "matrix.cpp",
    "denseMatrix.cpp",
    "sparseCSRMatrix.cpp",
    "sparseDOKMatrix.cpp",
    "sparseIJVMatrix.cpp",
    "sparseVVPMatrix.cpp",
)

def make(ctx):
    ctx.objects(
        source=source_files,
        target="matrices"
    )

debug = build = make
