
def options(opt):
    opt.decomposers.add_option("--skip-parmetis", action="store_true", default=False, help="Skip search for ParMetis library.")

def configure(ctx):
    if (ctx.options.skip_parmetis):
        return
    fragment = "#include \"metis.h\"\nint main(int argc, char** argv) {{ return IDXTYPEWIDTH != {0}; }}\n".format(ctx.options.intwidth)
    ctx.check_cxx(mandatory=False, fragment=fragment, msg="Checking for 'parmetis'", okmsg="parmetis", define_name="HAVE_PARMETIS", header_name="parmetis.h", lib="parmetis", uselib_store="PARMETIS", execute=True)
