
def options(opt):
    opt.decomposers.add_option("--skip-parmetis", action="store_true", default=False, help="Skip search for ParMetis library.")

def configure(ctx):
    if (ctx.options.skip_parmetis):
        return
    if "HAVE_METIS" in ctx.env:
        ctx.check_cxx(mandatory=False, msg="Checking for 'parmetis'", okmsg="parmetis", define_name="HAVE_PARMETIS", header_name="parmetis.h", lib="parmetis", uselib_store="PARMETIS")
