
def options(opt):
    opt.solvers.add_option("--hypre", action="store", type="string", metavar="HYPRE_ROOT", default="", help="Path to HYPRE solver.")

def configure(ctx):
    if int(ctx.options.intwidth) == 32:
        ctx.link_cxx(name="hypre", header_name="HYPRE.h", libs=["HYPRE", "HYPRE_core"], root=ctx.options.hypre)