
ESDATA = "input_esdata"

source_files = (
    "esdata.cpp",
)

def configure(ctx):
    ctx.setenv(ESDATA, ctx.all_envs[""].derive());

def build(ctx):
    ctx.env = ctx.all_envs[ESDATA]

    ctx.lib(
        source          = source_files,
        target          = "esinput_esdata",
        use             = "espreso_includes",
        install_path    = ctx.LIBRARIES
    )
