
import os.path
import glob

def configure(ctx):
    vtklibs = glob.glob("/home/mec059/projects/vtk/install/lib/*.so")
    vtklibs = [ lib.split('/')[-1].lstrip("lib").rstrip(".so") for lib in vtklibs ]
    ctx.env.append_unique("LIB", vtklibs)

def build(ctx):
    ctx.objects(
        source = ctx.path.ant_glob('**/*.cpp'),
        target = "generic_out",
        use    = "espreso_includes"
    )
