
def options(opt):
    pass

def configure(ctx):
    ctx.env.NVCC = ctx.find_program("nvcc")
    ctx.env.NVCCFLAGS = [ "-std=c++17", "-arch=native", "-O2", "-Xcompiler", "-fPIC" ]

    headers = [ "cuda_runtime.h" ]
    libs = [ "cudart", "cusparse", "cublas", "cusolver" ]
    ctx.check_cxx(mandatory=False, msg="Checking for 'cuda'", okmsg=" ".join(libs), define_name="HAVE_CUDA", header_name=headers, lib=libs, uselib_store="CUDA")
