
#ifndef SRC_CONFIGURATION_PHYSICS_H_
#define SRC_CONFIGURATION_PHYSICS_H_

enum class PHYSICS {
	ADVECTION_DIFFUSION_2D,
	ADVECTION_DIFFUSION_3D,
	STRUCTURAL_MECHANICS_2D,
	STRUCTURAL_MECHANICS_3D,
	SHALLOW_WATER_2D,
	SIZE
};


#endif /* SRC_CONFIGURATION_PHYSICS_H_ */
