
#ifndef SRC_CONFIGURATION_PHYSICS_H_
#define SRC_CONFIGURATION_PHYSICS_H_

enum class PHYSICS {
	LINEAR_ELASTICITY_2D,
	LINEAR_ELASTICITY_3D,
	TRANSIENT_ELASTICITY_2D,
	TRANSIENT_ELASTICITY_3D,
	ADVECTION_DIFFUSION_2D,
	ADVECTION_DIFFUSION_3D,
	SHALLOW_WATER_2D,
	STOKES,
	SIZE
};


#endif /* SRC_CONFIGURATION_PHYSICS_H_ */
