
from waflib.Tools.ccroot import link_task

class cxxprogram(link_task):
    run_str='${LINK_CXX} ${LINKFLAGS} ${CXXLNK_SRC_F}${SRC} ${CXXLNK_TGT_F}${TGT[0].abspath()} ${RPATH_ST:RPATH} ${FRAMEWORKPATH_ST:FRAMEWORKPATH} ${FRAMEWORK_ST:FRAMEWORK} ${ARCH_ST:ARCH} ${SHLIB_MARKER} ${LIBPATH_ST:LIBPATH} ${LIB_ST:LIB} ${LDFLAGS} ${STLIB_MARKER} ${STLIBPATH_ST:STLIBPATH} ${STLIB_ST:STLIB} -Wl,-Bdynamic'
    vars=['LINKDEPS']
    ext_out=['.bin']
    inst_to='${BINDIR}'

source_files = (
    "src/main.cpp",
)

def configure(ctx):
    pass

def build(ctx):
    ctx.program(
        source=source_files,
        target="espreso",
        use="espreso_includes mesh_includes solver_includes pmcube_includes bem_includes esmesh essolver espmcube esbem",
        install_path=ctx.ROOT
    )
