
PERMONCUBE = "permoncube"

source_files = (
    "elements/3D/tetrahedron4.cpp",
    "elements/3D/tetrahedron10.cpp",
    "elements/3D/hexahedron8.cpp",
    "elements/3D/hexahedron20.cpp",
    "elements/3D/prisma6.cpp",
    "elements/3D/prisma15.cpp",
    "elements/3D/pyramid5.cpp",
    "elements/3D/pyramid13.cpp",
    "factory/factory.cpp",
    "factory/settings.cpp",
    "cube/settings.cpp",
    "generator.cpp",
)

def configure(ctx):
    ctx.setenv(PERMONCUBE, ctx.all_envs[""].derive());

def build(ctx):
    ctx.env = ctx.all_envs[PERMONCUBE]

    ctx.lib(
        source          = source_files,
        target          = "espmcube",
        use             = "espreso_includes mesh_includes bem_includes",
        install_path    = ctx.LIBRARIES
    )

    ctx(
        export_includes = "src",
        name            = "pmcube_includes"
    )
