
source_files = (
   "HTFETI-seq.cpp",
   "Cluster.cpp",
   "ConfigFile.cpp",
   "Domain.cpp",
   "FEM_Assembler.cpp",
   "IterSolver.cpp",
   "SparseDSS.cpp",
   "SparseMatrix.cpp",
   "SparseSolver.cpp",
   "TimeEval.cpp",
   "utils.cpp"
)

def build(ctx):
    ctx.shlib(
        source=source_files,
        target="essolver"
    )