
source_files = (
    "matrices/denseMatrix.cpp",
    "matrices/matrix.cpp",
)

def configure(ctx):
    pass

def build(ctx):
    ctx.lib(
        source          = source_files,
        target          = "esbasis",
        install_path    = ctx.LIBRARIES
    )
