
BASIS = "basis"

source_files = (
    "matrices/denseMatrix.cpp",
    "matrices/matrix.cpp",
)

def configure(ctx):
    ctx.setenv(BASIS, ctx.all_envs[""].derive());

def build(ctx):
    ctx.env = ctx.all_envs[BASIS]

    ctx.lib(
        source          = source_files,
        target          = "esbasis",
        install_path    = ctx.LIBRARIES
    )

    ctx(
        export_includes = ".",
        name            = "basis_includes"
    )
