
def configure(ctx):
    ctx.env.append_unique("STLIB", [ "HYPRE" ])

def build(ctx):
    ctx.objects(
        source = ctx.path.ant_glob('**/*.cpp'),
        target = "assembler",
        use    = "espreso_includes"
    )
