
source_files =  (
    "coordinates.cpp",
    "mesh.cpp",
    "faces.cpp",
    "corners.cpp",
    "boundaries.cpp",
)

def make(ctx):
    ctx.objects(
        source=source_files,
        target="structures"
    )

debug = build = make
