
#ifndef SRC_CONFIG_PHYSICS_H_
#define SRC_CONFIG_PHYSICS_H_

enum class PHYSICS {
	LINEAR_ELASTICITY_2D,
	LINEAR_ELASTICITY_3D,
	TRANSIENT_ELASTICITY_2D,
	TRANSIENT_ELASTICITY_3D,
	ADVECTION_DIFFUSION_2D,
	ADVECTION_DIFFUSION_3D,
	STOKES,
	SIZE
};


#endif /* SRC_CONFIG_PHYSICS_H_ */
