
CONFIG = "config"

source_files = (
    "esconfig.cpp",
)

def configure(ctx):
    ctx.setenv(CONFIG, ctx.all_envs[""].derive());

def build(ctx):
    ctx.env = ctx.all_envs[CONFIG]

    ctx.lib(
        source          = source_files,
        target          = "esconfig",
        install_path    = ctx.LIBRARIES
    )
