
source_files = (
    "esconfig.cpp",
)

def configure(ctx):
    pass

def build(ctx):
    ctx.lib(
        source          = source_files,
        target          = "esconfig",
        install_path    = ctx.LIBRARIES
    )
