
import os

def options(opt):
    opt.compiler.add_option("--arch",
        action="store",
        type="string",
        metavar="ARCH",
        default=os.getenv("ARCH"),
        help="Set vectorized instruction set.")

def configure(ctx):
    if ctx.options.arch == "native":
        ctx.env.append_unique("CXXFLAGS", [ "-march=native" ])
    if ctx.options.arch == "aarch64":
        if ctx.options.flavor == "fujitsu":
            ctx.env.append_unique("CXXFLAGS", [ "-march=armv8.2-a+sve", "-D__ARM_FEATURE_SVE_BITS=512", "-KSVE", "-KA64FX", "-Kfast" ])
        else:
            ctx.env.append_unique("CXXFLAGS", [ "-mcpu=a64fx", "-msve-vector-bits=512" ])

    # Check SIMD instruction set
    code = '''
        #include <cstdio>
        int main() {
        #if defined(__AVX512F__) && defined(__AVX512DQ__)
        printf("AVX512");
        #elif defined(__AVX__)
        printf("AVX");
        #elif defined(__SSE2__)
        printf("SSE2");
        #elif defined(__ARM_FEATURE_SVE)
        printf("SVE");
        #else
        printf("NONE");
        #endif
        return 0;
        }
    '''

    svesize = '''
        #include <cstdio>
        #include <arm_sve.h>
        int main(int argc, char **argv)
        {
            printf("%d", __ARM_FEATURE_SVE_BITS);
            return 0;
        }
    '''

    svefixed = '''
        #include <arm_sve.h>
        typedef svfloat64_t VEC __attribute__((arm_sve_vector_bits(512)));
        int main(int argc, char **argv)
        {
            struct { VEC vec; } value;
            return 0;
        }
    '''

    ctx.env.SIMD = ctx.check_cxx(
        mandatory   = False,
        msg         = 'Checking for SIMD intrinsics',
        fragment    = code,
        define_ret  = True,
        execute     = True,
        okmsg       = lambda ret: str(ret["success"]))

    if ctx.env.SIMD == "SVE":
        size = ctx.check_cxx(
            msg         = 'Checking for SVE vector length',
            fragment    = svesize,
            define_ret  = True,
            execute     = True,
            okmsg       = lambda ret: str(ret["success"]))

        fixedsize = ctx.check_cxx(
            msg         = 'Checking for SVE of fixed size',
            mandatory   = False,
            fragment    = svefixed)

        if fixedsize:
            ctx.env.append_unique("CXXFLAGS", [ "-DSIMD_ARM_SVE_GENERAL" ])
        else:
            ctx.env.append_unique("CXXFLAGS", [ "-DSIMD_ARM_SVE_ARRAY" + size ])

    ctx.env.SIMD_ASSEMBLER = ctx.env.SIMD
    if ctx.options.simd_off:
        ctx.env.SIMD_ASSEMBLER = "AUTO"
