
source_files = (
    "Assembler.cpp",
    "BoundaryCondition.cpp",
    "BoundaryCondOnFace.cpp",
    "BSparse.cpp",
    "BSparseC.cpp",
    "Cluster_g.cpp",
    "ContactBC.cpp",
    "Coordinate.cpp",
    "CoupleIntDouble.cpp",
    "CustomData.cpp",
    "Data.cpp",
    "DirichletBC.cpp",
    "Domain_g.cpp",
    "ElementLibrary.cpp",
    "Fem.cpp",
    "KSparse.cpp",
    "LinearAlgebra.cpp",
    "main.cpp",
    "Mesh.cpp",
    "NeumannBC.cpp",
    "RectangularFace.cpp",
    "RSparse.cpp",
    "SaveFEM.cpp",
    "Solid45.cpp",
    "Solid45EqNumbGlobal.cpp",
    "Solid45NodNumbLoc.cpp",
    "Solver.cpp",
    "StiffnessLocal.cpp",
    "Test.cpp",
    "utility.cpp"
)

def build(ctx):
    ctx.shlib(
        source=source_files,
        target="espmcube",
        use="mesh_includes"
    )
