
#include "configuration.h"

void Configuration::_fillDefaultValues()
{
	_parameters[CMD_LINE_ARGUMENTS] = new StringParameter("CMD_LINE_ARGUMENTS", "Specifies parameters set from command line arguments.", "");

	_parameters[ANSYS_DIR] = new StringParameter("ANSYS_DIR", "A root directory for ANSYS input files.", "");

	_parameters[ANSYS_DIRICHLET_X] = new StringParameter("ANSYS_DIRICHLET_X", "A file with dirichlet condition in x-axis.", "");
	_parameters[ANSYS_DIRICHLET_Y] = new StringParameter("ANSYS_DIRICHLET_Y", "A file with dirichlet condition in y-axis.", "");
	_parameters[ANSYS_DIRICHLET_Z] = new StringParameter("ANSYS_DIRICHLET_Z", "A file with dirichlet condition in z-axis.", "");

	_parameters[ANSYS_FORCES_X] = new StringParameter("ANSYS_FORCES_X", "A file with forces in x-axis.", "");
	_parameters[ANSYS_FORCES_Y] = new StringParameter("ANSYS_FORCES_Y", "A file with forces in y-axis.", "");
	_parameters[ANSYS_FORCES_Z] = new StringParameter("ANSYS_FORCES_Z", "A file with forces in z-axis.", "");

	_parameters[PMCUBE_ELEMENT_TYPE] = new IntegerParameter("PMCUBE_ELEMENT_TYPE", "The type of elements generated by PermonCube.", 0);

	_parameters[PMCUBE_CLUSTERS_X] = new IntegerParameter("PMCUBE_CLUSTERS_X", "Number of clusters in x-axis.", 1);
	_parameters[PMCUBE_CLUSTERS_Y] = new IntegerParameter("PMCUBE_CLUSTERS_Y", "Number of clusters in y-axis.", 1);
	_parameters[PMCUBE_CLUSTERS_Z] = new IntegerParameter("PMCUBE_CLUSTERS_Z", "Number of clusters in z-axis.", 1);

	_parameters[PMCUBE_SUBDOMAINS_X] = new IntegerParameter("PMCUBE_SUBDOMAINS_X", "Number of sub-domains in x-axis.", 2);
	_parameters[PMCUBE_SUBDOMAINS_Y] = new IntegerParameter("PMCUBE_SUBDOMAINS_Y", "Number of sub-domains in y-axis.", 2);
	_parameters[PMCUBE_SUBDOMAINS_Z] = new IntegerParameter("PMCUBE_SUBDOMAINS_Z", "Number of sub-domains in z-axis.", 2);

	_parameters[PMCUBE_ELEMENTS_X] = new IntegerParameter("PMCUBE_ELEMENTS_X", "Number of elements in x-axis.", 5);
	_parameters[PMCUBE_ELEMENTS_Y] = new IntegerParameter("PMCUBE_ELEMENTS_Y", "Number of elements in y-axis.", 5);
	_parameters[PMCUBE_ELEMENTS_Z] = new IntegerParameter("PMCUBE_ELEMENTS_Z", "Number of elements in z-axis.", 5);

	_parameters[PMCUBE_FIX_ZERO_PLANES] = new BooleanParameter("PMCUBE_FIX_ZERO_PLANES", "Dirichlet is set to all nodes in zero planes.", false);
	_parameters[PMCUBE_FIX_BOTTOM] = new BooleanParameter("PMCUBE_FIX_BOTTOM", "Dirichlet is set to all nodes in the bottom plane.", true);

	_parameters[SOLVER_ITERATIONS] = new IntegerParameter("SOLVER_ITERATIONS", "Number of solver iterations.", 100);
}

Configuration::Configuration(std::string configFile): _parameters(ATTRIBUTES_COUNT)
{
	_fillDefaultValues();

	std::ifstream file(configFile);

	if (file.is_open()) {
		std::string line;

		while (getline(file, line, '\n')) {
			if (!line.size() || line.compare(0, 1, "#") == 0) {
				continue;
			}
			size_t pos = line.find("#");
			if (pos < std::string::npos) {
				line = line.substr(0, pos);
			}
			for (size_t i = 0; i < _parameters.size(); i++) {
				if (_parameters[i]->match(line)) {
					_parameters[i]->set(line);
					break;
				}
				if (i == _parameters.size() - 1) {
					std::cerr << "Unknown parameter in configuration file: " << line << ".\n";
					exit(EXIT_FAILURE);
				}
			}
		}

		file.close();
	} else {
		std::cout << "File '" << configFile << "' not found.\n";
	}
}

void Configuration::print()
{
	for (size_t i = 0; i < _parameters.size(); i++) {
		std::cout << _parameters[i]->name() << " = ";
		switch (_parameters[i]->type()) {
			case STRING_PARAMETER: {
				std::cout << "'" << value<std::string>(i) << "'";
				break;
			}
			case INTEGER_PARAMETER: {
				std::cout << value<eslocal>(i);
				break;
			}
			case BOOLEAN_PARAMETER: {
				std::cout << value<bool>(i);
				break;
			}
		}
		std::cout << "\n";
	}
}

void Configuration::description()
{
	for (size_t i = 0; i < _parameters.size(); i++) {
		std::cout << _parameters[i]->name() << ": " << _parameters[i]->description() << "\n";
	}
}

template<>
eslocal Configuration::value<eslocal>(InputParameter parameter)
{
	if (_parameters[parameter]->type() == INTEGER_PARAMETER) {
		return static_cast<IntegerParameter*>(_parameters[parameter])->get();
	} else {
		std::cerr << "Invalid parameter type. ";
		std::cerr << _parameters[parameter]->name() << " is integer value.";
		exit(EXIT_FAILURE);
	}
}

template<>
std::string Configuration::value<std::string>(InputParameter parameter)
{
	if (_parameters[parameter]->type() == STRING_PARAMETER) {
		return static_cast<StringParameter*>(_parameters[parameter])->get();
	} else {
		std::cerr << "Invalid parameter type. ";
		std::cerr << _parameters[parameter]->name() << " is string value.";
		exit(EXIT_FAILURE);
	}
}

template<>
bool Configuration::value<bool>(InputParameter parameter)
{
	if (_parameters[parameter]->type() == BOOLEAN_PARAMETER) {
		return static_cast<BooleanParameter*>(_parameters[parameter])->get();
	} else {
		std::cerr << "Invalid parameter type. ";
		std::cerr << _parameters[parameter]->name() << " is boolean value.";
		exit(EXIT_FAILURE);
	}
}


