
source_files = (
    "main.cpp",
)

def build(ctx):
    ctx.program(
        source=source_files,
        target="espreso",
        lib="metis",
        use="mesh_includes solver_includes pmcube_includes esmesh essolver espmcube"
    )