
def options(opt):
    pass

def configure(ctx):
    ctx.link_cxx(name="ssllapack", header_name=["lapacke.h"], libs=["fjlapacksve", "fj90f", "fj90i", "fj90f", "fj90rt", "fjsrcinfo", "elf", "m", "pthread"])
