
def options(opt):
    opt.decomposers.add_option("--skip-kahip", action="store_true", default=False, help="Skip search for KaHIP library.")

def configure(ctx):
    if (ctx.options.skip_kahip):
        return
    ctx.check_cxx(mandatory=False, msg="Checking for 'kahip'", okmsg="kahip", define_name="HAVE_KAHIP", header_name="kaHIP_interface.h", lib="kahip", uselib_store="KAHIP", global_define=0)