
VTK = "output_vtk"

source_files = (
    "vtk.cpp",
)

def configure(ctx):
    ctx.setenv(VTK, ctx.all_envs[""].derive());

def build(ctx):
    ctx.env = ctx.all_envs[VTK]

    ctx.lib(
        source          = source_files,
        target          = "esoutput_vtk",
        use             = "espreso_includes",
        install_path    = ctx.LIBRARIES
    )
