sudo: required
dist: trusty

language: cpp
comiler:
 - gcc
 - clang

before_install:
 - sudo apt-get update -qq

install:
 - sudo apt-get install -qq mpich cmake

script:
 - mkdir build && cd build && cmake ../ && make && make test
 - cd $TRAVIS_BUILD_DIR
 - mkdir build_nompi && cd build_nompi && cmake ../ -DUSE_MPI=OFF && make && make test
 - cd $TRAVIS_BUILD_DIR
