C
C  This file is part of MUMPS 5.0.1, released
C  on Thu Jul 23 17:08:29 UTC 2015
C
C
C  Copyright 1991-2015 CERFACS, CNRS, ENS Lyon, INP Toulouse, Inria,
C  University of Bordeaux.
C
C  This version of MUMPS is provided to you free of charge. It is
C  released under the CeCILL-C license:
C  http://www.cecill.info/licences/Licence_CeCILL-C_V1-en.html
C
      MODULE TOOLS_COMMON
      INTERFACE MUMPS_REALLOC
      SUBROUTINE MUMPS_IREALLOC(ARRAY, MINSIZE, INFO, LP, FORCE, COPY,
     &     STRING, MEMCNT, ERRCODE)
      INTEGER, POINTER    :: ARRAY(:)
      INTEGER             :: MINSIZE, LP
      INTEGER             :: INFO(:)
      LOGICAL, OPTIONAL   :: FORCE
      LOGICAL, OPTIONAL   :: COPY
      CHARACTER, OPTIONAL :: STRING*(*)
      INTEGER, OPTIONAL   :: ERRCODE, MEMCNT
      END SUBROUTINE MUMPS_IREALLOC
      SUBROUTINE MUMPS_DREALLOC(ARRAY, MINSIZE, INFO, LP, FORCE, COPY,
     &     STRING, MEMCNT, ERRCODE)
      REAL(kind(1.D0)), POINTER    :: ARRAY(:)
      INTEGER             :: MINSIZE, LP
      INTEGER             :: INFO(:)
      LOGICAL, OPTIONAL   :: FORCE
      LOGICAL, OPTIONAL   :: COPY
      CHARACTER, OPTIONAL :: STRING*(*)
      INTEGER, OPTIONAL   :: ERRCODE, MEMCNT
      END SUBROUTINE MUMPS_DREALLOC
      SUBROUTINE MUMPS_SREALLOC(ARRAY, MINSIZE, INFO, LP, FORCE, COPY,
     &     STRING, MEMCNT, ERRCODE)
      REAL(kind(1.E0)), POINTER    :: ARRAY(:)
      INTEGER             :: MINSIZE, LP
      INTEGER             :: INFO(:)
      LOGICAL, OPTIONAL   :: FORCE
      LOGICAL, OPTIONAL   :: COPY
      CHARACTER, OPTIONAL :: STRING*(*)
      INTEGER, OPTIONAL   :: ERRCODE, MEMCNT
      END SUBROUTINE MUMPS_SREALLOC
      SUBROUTINE MUMPS_ZREALLOC(ARRAY, MINSIZE, INFO, LP, FORCE, COPY,
     &     STRING, MEMCNT, ERRCODE)
      COMPLEX(kind((1.D0,1.D0))), POINTER    :: ARRAY(:)
      INTEGER             :: MINSIZE, LP
      INTEGER             :: INFO(:)
      LOGICAL, OPTIONAL   :: FORCE
      LOGICAL, OPTIONAL   :: COPY
      CHARACTER, OPTIONAL :: STRING*(*)
      INTEGER, OPTIONAL   :: ERRCODE, MEMCNT
      END SUBROUTINE MUMPS_ZREALLOC
      SUBROUTINE MUMPS_CREALLOC(ARRAY, MINSIZE, INFO, LP, FORCE, COPY,
     &     STRING, MEMCNT, ERRCODE)
      COMPLEX(kind((1.E0,1.E0))), POINTER    :: ARRAY(:)
      INTEGER             :: MINSIZE, LP
      INTEGER             :: INFO(:)
      LOGICAL, OPTIONAL   :: FORCE
      LOGICAL, OPTIONAL   :: COPY
      CHARACTER, OPTIONAL :: STRING*(*)
      INTEGER, OPTIONAL   :: ERRCODE, MEMCNT
      END SUBROUTINE MUMPS_CREALLOC
      END INTERFACE
      END MODULE
