
PERMONCUBE = "base"

source_files = (
    "src/permoncube.cpp",
)

def configure(ctx):
    pass

def build(ctx):
    ctx.env = ctx.all_envs[PERMONCUBE]

    if ctx.options.permoncube:
        ctx.program(
            source=source_files + ("src/main.cpp",),
            target="espmcube",
            use="mesh_includes esmesh esbem",
            install_path=ctx.ROOT
        )
    else:
        ctx.shlib(
            source=source_files,
            target="espmcube",
            use="mesh_includes esmesh",
            install_path=ctx.ROOT + "/libs"
        )


    ctx(
        export_includes = "src",
        name            = "pmcube_includes"
    )
