
PERMONCUBE = "permoncube"

source_files = (
    "src/elements/3D/tetrahedron4.cpp",
    "src/elements/3D/tetrahedron10.cpp",
    "src/elements/3D/hexahedron8.cpp",
    "src/elements/3D/hexahedron20.cpp",
    "src/elements/3D/prisma6.cpp",
    "src/elements/3D/prisma15.cpp",
    "src/elements/3D/pyramid5.cpp",
    "src/elements/3D/pyramid13.cpp"
)

def configure(ctx):
    ctx.setenv(PERMONCUBE, ctx.all_envs[""].derive());

def build(ctx):
    ctx.env = ctx.all_envs[PERMONCUBE]

    if ctx.options.permoncube:
        ctx.program(
            source          = source_files + ("src/main.cpp",),
            target          = "espmcube",
            use             = "mesh_includes esmesh esbem",
            install_path    = ctx.ROOT
        )
    else:
        ctx.lib(
            source          = source_files,
            target          = "espmcube",
            use             = "espreso_includes mesh_includes bem_includes",
            install_path    = ctx.ROOT + "/libs"
        )


    ctx(
        export_includes = "src",
        name            = "pmcube_includes"
    )
