
source_files = (
    "settings.cpp",
    "loader.cpp",
)

def build(ctx):
    ctx.recurse("elements")
    ctx.recurse("matrices")
    ctx.recurse("structures")

    ctx.shlib(
        source=source_files,
        target="esmesh",
        lib="metis",
        use="elements matrices structures",
    )

    #ctx.program(
    #    source=source_files + ("main.cpp", ),
    #    target="esmesh",
    #    use="elements matrices structures",
    #)
