
import os
import glob

def configure(ctx):
    ctx.env.append_unique("CXXFLAGS", [ "-I" + include for include in ctx.env["PARAVIEW::INCLUDE"] ])
    ctx.env.append_unique("LIBPATH", ctx.env["PARAVIEW::LIBPATH"])

    includes = []
    for file in glob.glob(ctx.path.abspath() + "/*.h") + glob.glob(ctx.path.abspath() + "/*.cpp"):
        for line in open(file, "r"):
            if line.find("#include") != -1:
                if line.find("vtk") != -1:
                    includes += [ line ]

    ctx.env.PARAVIEW = ctx.check_cc(
        fragment    = "{0}int main() {{ return 0; }}\n".format("".join(includes)),
        mandatory   = False,
        execute     = False,
        msg         = "Checking for Paraview headers",
        errmsg      = "not found - set path to Paraview headers (parameter PARAVIEW::INCLUDE)",
        okmsg       = "found"
    )

    vtklibs = []
    if len(ctx.env["PARAVIEW::LIBPATH"]) == 1:
        vtklibs = [ lib.split('/')[-1][3:-3] for lib in glob.glob(ctx.env["PARAVIEW::LIBPATH"][0] + "/*.so") ]

    ctx.start_msg("Checking for Paraview libraries")
    if len(vtklibs) and any(lib.startswith("vtk") for lib in vtklibs):
        ctx.end_msg("found")
    else:
        ctx.end_msg("not found - set path to Paraview libraries (parameter PARAVIEW::LIBPATH)", color='YELLOW')
        ctx.env.PARAVIEW = False

    ctx.env.append_unique("LIB", vtklibs)

    if ctx.env.PARAVIEW:
        ctx.env.append_unique("DEFINES", [ "HAVE_PARAVIEW" ])

def build(ctx):
    if ctx.env.PARAVIEW:
        ctx.objects(
            source = ctx.path.ant_glob('*.cpp') + ctx.path.ant_glob('libparaview/*.cpp'),
            target = "paraview_out",
            use    = "espreso_includes"
        )
    else:
        ctx.objects(
            source = ctx.path.ant_glob('*.cpp') + ctx.path.ant_glob('espreso/*.cpp'),
            target = "paraview_out",
            use    = "espreso_includes"
        )
