
def options(opt):
    opt.math.add_option("--skip-suitesparse", action="store_true", default=False, help="Skip search for SuiteSparse libraries.")

def configure(ctx):
    if (ctx.options.skip_suitesparse):
        return

    headers_direct = "cholmod.h"
    headers_subdir = "suitesparse/cholmod.h"
    libs = ["cholmod"]
    if ctx.check_cxx(mandatory=False, msg="Checking for 'suitesparse'", okmsg=" ".join(libs), define_name="HAVE_SUITESPARSE", header_name=headers_direct, lib=libs, uselib_store="SUITESPARSE"):
        ctx.env.append_unique("DEFINES", "SUITESPARSE_HEADER_DIRECT")
    elif ctx.check_cxx(mandatory=False, msg="Checking for 'suitesparse'", okmsg=" ".join(libs), define_name="HAVE_SUITESPARSE", header_name=headers_subdir, lib=libs, uselib_store="SUITESPARSE"):
        ctx.env.append_unique("DEFINES", "SUITESPARSE_HEADER_SUBDIR")
