
def configure(ctx):
    ctx.recurse("esdata")
    ctx.recurse("ansys")
    ctx.recurse("generator")
    ctx.recurse("openfoam")
    ctx.recurse("api")

def build(ctx):
    ctx.recurse("esdata")
    ctx.recurse("ansys")
    ctx.recurse("generator")
    ctx.recurse("openfoam")
    ctx.recurse("api")

    ctx.objects(
        source = ctx.path.ant_glob('*.cpp'),
        target = "loader",
        use    = "espreso_includes"
    )
