
def configure(ctx):
    ctx.recurse("esdata")
    ctx.recurse("ansys")
    ctx.recurse("meshgenerator")
    ctx.recurse("generator")
    ctx.recurse("openfoam")
    ctx.recurse("api")

def build(ctx):
    ctx.recurse("esdata")
    ctx.recurse("ansys")
    ctx.recurse("meshgenerator")
    ctx.recurse("generator")
    ctx.recurse("openfoam")
    ctx.recurse("api")
